#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

version: '1.0.0-dev.{build}'

shallow_clone: true

build: off

os:
  - Visual Studio 2015

environment:
  INTERPRETERS: '!beam,!hbase,!pig,!jdbc,!file,!flink,!ignite,!kylin,!lens,!cassandra,!elasticsearch,!bigquery,!alluxio,!scio,!livy,!groovy,!sap,!java,!geode,!neo4j,!hazelcastjet,!submarine,!sparql,!mongodb'
  matrix:
    - BUILD_FLAG: clean package -Pbuild-distr -DskipTests
      TEST_FLAG: package -Pbuild-distr -DskipTests

init:
  - git config --global core.autocrlf true

cache:
  - C:\maven\apache-maven-3.2.5
  - C:\Users\appveyor\.m2
  - zeppelin-web\node
  - zeppelin-web\node_modules

install:
  - echo "Install"
  - cmd: SET M2_HOME=C:\maven\apache-maven-3.2.5
  - cmd: SET GROOVY_HOME=C:\groovy\groovy-2.4.8
  - cmd: SET PATH=%GROOVY_HOME%\bin;%JAVA_HOME%\bin;%M2_HOME%\bin;%PATH%
  - cmd: mvn --version
  - cmd: java -version
  - ps: |     
      if (Test-Path env:SPARK_VER) {
        $SPARK_VERSION = $env:SPARK_VER
        $HADOOP_VERSION = $env:HADOOP_VER
        $SPARK_ARCHIVE = "spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION"
        (new-object System.Net.WebClient).DownloadFile(
          $('http://archive.apache.org/dist/spark/spark-' + $SPARK_VERSION + '/' + $SPARK_ARCHIVE + '.tgz'),
          $($SPARK_ARCHIVE + '.tgz')
        )
        $cont=true
        7z x $($SPARK_ARCHIVE+'.tgz') 
        7z x $($SPARK_ARCHIVE+'.tar')
      }
      
build_script:
  - echo "Build  mvn %BUILD_FLAG% %MODULES% %PROFILE% -B"
  - cmd: mvn %BUILD_FLAG% %MODULES% %PROFILE% -B
  - ps: echo "Size of caches (bytes):"
  - ps: Get-ChildItem -Recurse 'C:\maven\apache-maven-3.2.5' | Measure-Object -Property Length -Sum
  - ps: Get-ChildItem -Recurse 'C:\Users\appveyor\.m2' | Measure-Object -Property Length -Sum
  - ps: Get-ChildItem -Recurse 'zeppelin-web\node' | Measure-Object -Property Length -Sum
  - ps: Get-ChildItem -Recurse 'zeppelin-web\node_modules' | Measure-Object -Property Length -Sum
test_script:
  - echo "Test mvn %TEST_FLAG% %TEST_MODULES% %PROFILE% -B %TEST_PROJECTS%"
  - cmd: mvn %TEST_FLAG% %TEST_MODULES% %PROFILE% -B %TEST_PROJECTS%
  